[package]
name = "cnewhope"
version = "0.1.0"
authors = ["quininer kel <quininer@live.com>"]
build = "build.rs"

[lib]
path = "lib.rs"

[build-dependencies]
cc = "1"

[dev-dependencies]
libc = "0.2"
rand = "0.3"
newhope = { path = "..", version = "0.2" }

[features]
tor = [ "newhope/tor" ]
